spring:
  application:
    name: Cinema Booking System
  profiles:
    active: default

  datasource:
    url: jdbc:postgresql://localhost:5433/cinema_booking_system
    username: gen
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Initial baseline"
    locations: classpath:db/migration,classpath:db/rollback
    schemas: public
    table: flyway_schema_history
    validate-on-migrate: true
    clean-disabled: false
    group: true
    mixed: true
    repeatable-sql-migration-prefix: R__
    out-of-order: false

  web:
    resources:
      add-mappings: false

logging:
  level:
    '[com.nostratech.excentis.configfile]': DEBUG
    '[org.springframework.security]': DEBUG
    '[com.gen.cinema]': DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

minio:
  internal-endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: cinema-media

mail:
  smtp:
    auth: true
    starttls:
      enable: true
    host: sandbox.smtp.mailtrap.io
    port: 465
    ssl:
      trust: sandbox.smtp.mailtrap.io
  username: 10d6a47ba0d890
  password: 1ad49dba18e691