spring:
  application:
    name: Cinema Booking System
  profiles:
    active: default

  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_booking_system
    username: gen
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Initial baseline"
    locations: classpath:db/migration,classpath:db/rollback
    schemas: public
    table: flyway_schema_history
    validate-on-migrate: true
    clean-disabled: false
    group: true
    mixed: true
    repeatable-sql-migration-prefix: R__
    out-of-order: false

logging:
  level:
    '[com.nostratech.excentis.configfile]': DEBUG
    '[org.springframework.security]': DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"